---
title: "Explore COVID-19 Data Sources"
author: "Nathan (Nat) Goodman"
date: "November 10, 2020"
output:
  pdf_document: default
  html_document:
    css: css/html_document.css
    highlight: kate
  github_document:
    html_preview: no
linkcolor: cyan
citecolor: green
urlcolor: blue
---
<!-- README.md is generated from README.Rmd. Please edit that file -->

A collection of R scripts and documents analyzing COVID-19 data sources and displaying counts of cases, hospital admissions, and deaths. The code focuses on Washington state where I live but also displays counts for select other USA locations.

**THE SOFTWARE IS A WORK IN PROGRESS. THE CODE IS ROUGH and SOFTWARE DOCUMENTATION NONEXISTENT. PLEASE GET IN TOUCH IF YOU NEED HELP**
**THE CURRENT VERSION  IS HIGHLY DEPENDENT ON MY DEVELOPMENT ENVIRONMENT. THERE'S LITTLE CHANCE OF ANYONE ELSE RUNNING THE CODE AS-IS. PLEASE GET IN TOUCH IF YOU NEED HELP**

## Installation and Usage

The software is **not a package** and cannot be installed by `devtools::install_github` or related. Sorry. The simplest way to get the software is to download or clone the entire repo.

More TBD.

## Comments Please!

Please post comments on [Twitter](https://twitter.com/gnatgoodman) or [Facebook](https://www.facebook.com/nathan.goodman.3367), or contact me by email [natg@shore.net](mailto:natg@shore.net). 

Please report bugs, other software problems, and feature requests using the [GitHub Issue Tracker](https://github.com/natgoodman/covid/issues). I will be notified, and you'll be apprised of progress. As already noted, the software is still rough and software documentation nonexistent.

## Copyright & License

Copyright (c) 2020 Nathan Goodman

The software is **open source and free**, released under the [MIT License](https://opensource.org/licenses/MIT). The documentation is **open access**, released under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0).
