---
output:
  pdf_document: default
  html_document: default
---
```{r echo=FALSE,include=FALSE,cache=FALSE}
## setup variables
source('R/dat.R');
doc='updat';
vsn=latest_version('doh',NULL,'data/doh');
```
---
title: "COVID-19 Counts in Washington State and Select Other Locations: Weekly Updates"
author: "Nathan (Nat) Goodman"
date: "`r format(as.Date(vsn,format='%y-%m-%d')+3,'%B %-d, %Y')`"
output:
  html_document:
    css: css/html_document.css
    highlight: kate
  pdf_document: default
linkcolor: cyan
citecolor: green
urlcolor: blue
---

*Counts of cases and deaths are key metrics of COVID-19 prevalence and burden, and are the basis for model-based estimates and predictions of these statistics. This page provides links to weekly updates that present graphs showing these metrics over time in Washington state and a few other USA locations of interest to me. I originally posted updates on Mondays but have switched to Wednesdays to accommodate changes in the Washington State Department of Health (DOH) data release schedule.*

`r paste(collapse='<br/>\n',paste('-',readLines('updat.link')))`<br/>

## Comments Please!

Please post comments on [LinkedIn](www.linkedin.com/in/gnatgoodman) or [Twitter](https://twitter.com/gnatgoodman).

## Copyright & License

Copyright (c) 2020-2021 Nathan Goodman

The software is **open source and free**, released under the [MIT License](https://opensource.org/licenses/MIT). The documentation is **open access**, released under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0).
